mysql:
  host: "0.0.0.0"
  port: 33306
  database: "go_chat"
  user: root
  password: "123456"

redis:
  host: "0.0.0.0"
  port: 6379
  user: root
  password: root

kafka:
  addr:
    - "localhost:9094"

es:
  url: "http://127.0.0.1:9201"
  sniff: false