// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zhuguangfeng/go-chat/cmd/server/app"
	activity2 "github.com/zhuguangfeng/go-chat/internal/event/activity"
	activity3 "github.com/zhuguangfeng/go-chat/internal/handler/v1/activity"
	dynamic2 "github.com/zhuguangfeng/go-chat/internal/handler/v1/dynamic"
	"github.com/zhuguangfeng/go-chat/internal/handler/v1/jwt"
	review2 "github.com/zhuguangfeng/go-chat/internal/handler/v1/review"
	user2 "github.com/zhuguangfeng/go-chat/internal/handler/v1/user"
	"github.com/zhuguangfeng/go-chat/internal/repository"
	"github.com/zhuguangfeng/go-chat/internal/repository/cache"
	"github.com/zhuguangfeng/go-chat/internal/repository/dao"
	"github.com/zhuguangfeng/go-chat/internal/service/activity"
	"github.com/zhuguangfeng/go-chat/internal/service/dynamic"
	"github.com/zhuguangfeng/go-chat/internal/service/review"
	"github.com/zhuguangfeng/go-chat/internal/service/user"
	"github.com/zhuguangfeng/go-chat/ioc"
)

// Injectors from wire.go:

func InitWebServer() *app.App {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedisCmd()
	jwtHandler := jwt.NewJwtHandler(cmdable)
	v := ioc.InitGinMiddleware(logger, jwtHandler)
	db := ioc.InitMysql()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(logger, userDao, userCache)
	userService := user.NewUserService(userRepository)
	userHandler := user2.NewUserController(jwtHandler, userService)
	dynamicDao := dao.NewDynamicDao(db)
	dynamicRepository := repository.NewDynamicRepository(dynamicDao)
	dynamicService := dynamic.NewDynamicService(dynamicRepository)
	dynamicHandler := dynamic2.NewDynamicHandler(dynamicService)
	activityDao := dao.NewActivityDao(db)
	reviewDao := dao.NewReviewDao(db)
	client := ioc.InitEsClient()
	activityEsDao := dao.NewActivityEsDao(client)
	activityRepository := repository.NewActivityRepository(logger, activityDao, reviewDao, activityEsDao)
	reviewRepository := repository.NewReviewRepository(logger, reviewDao)
	activitySignUpDao := dao.NewActivitySignUp(db)
	activitySignupRepository1 := repository.NewActivitySignupRepository(activitySignUpDao)
	activityService := activity.NewActivityService(logger, activityRepository, userRepository, reviewRepository, activitySignupRepository1)
	saramaClient := ioc.InitKafka()
	syncProducer := ioc.InitSaramaSyncProducer(saramaClient)
	producer := activity2.NewProducer(syncProducer)
	reviewService := review.NewReviewService(logger, reviewRepository, activityRepository, producer)
	activityHandler := activity3.NewActivityHandler(logger, activityService, userService, reviewService)
	reviewHandler := review2.NewReviewHandler(reviewService)
	engine := ioc.InitWebServer(v, userHandler, dynamicHandler, activityHandler, reviewHandler)
	activityConsumer := activity2.NewActivityConsumer(saramaClient, logger, activityRepository)
	v2 := ioc.NewConsumers(activityConsumer)
	appApp := &app.App{
		Server:    engine,
		Consumers: v2,
	}
	return appApp
}
